// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// Address is an autogenerated mock type for the Address type
type Address struct {
	mock.Mock
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *Address) FindByUserID(ctx context.Context, userID string) ([]domain.Address, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []domain.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Address, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Address); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasAddresses provides a mock function with given fields: ctx, userID
func (_m *Address) HasAddresses(ctx context.Context, userID string) (bool, string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for HasAddresses")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Insert provides a mock function with given fields: ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone
func (_m *Address) Insert(ctx context.Context, userID string, addressType domain.AddressType, country string, city string, state string, zip string, mainStreet string, secondaryStreet string, numeration string, phone string) (string, error) {
	ret := _m.Called(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AddressType, string, string, string, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AddressType, string, string, string, string, string, string, string, string) string); ok {
		r0 = rf(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AddressType, string, string, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone
func (_m *Address) Update(ctx context.Context, id string, userID string, addressType domain.AddressType, country string, city string, state string, zip string, mainStreet string, secondaryStreet string, numeration string, phone string) error {
	ret := _m.Called(ctx, id, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.AddressType, string, string, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddress creates a new instance of Address. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddress(t interface {
	mock.TestingT
	Cleanup(func())
}) *Address {
	mock := &Address{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
