// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

// Activate provides a mock function with given fields: ctx, userID, activationCode
func (_m *Auth) Activate(ctx context.Context, userID string, activationCode string) error {
	ret := _m.Called(ctx, userID, activationCode)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, activationCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForgotPassword provides a mock function with given fields: ctx, email
func (_m *Auth) ForgotPassword(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Auth) Login(ctx context.Context, email string, password string) (string, domain.Session, domain.User, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 domain.Session
	var r2 domain.User
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, domain.Session, domain.User, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) domain.Session); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(domain.Session)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) domain.User); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Get(2).(domain.User)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, email, password)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ResetPassword provides a mock function with given fields: ctx, userID, password, confirmPassword
func (_m *Auth) ResetPassword(ctx context.Context, userID string, password string, confirmPassword string) error {
	ret := _m.Called(ctx, userID, password, confirmPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, password, confirmPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Signup provides a mock function with given fields: ctx, firstName, lastName, email, password, confirmPassword
func (_m *Auth) Signup(ctx context.Context, firstName string, lastName string, email string, password string, confirmPassword string) (string, error) {
	ret := _m.Called(ctx, firstName, lastName, email, password, confirmPassword)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, firstName, lastName, email, password, confirmPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) string); ok {
		r0 = rf(ctx, firstName, lastName, email, password, confirmPassword)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, firstName, lastName, email, password, confirmPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuth creates a new instance of Auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auth {
	mock := &Auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
