// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// Basket is an autogenerated mock type for the Basket type
type Basket struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, basketID, productID
func (_m *Basket) AddItem(ctx context.Context, basketID string, productID string) (domain.Basket, error) {
	ret := _m.Called(ctx, basketID, productID)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 domain.Basket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Basket, error)); ok {
		return rf(ctx, basketID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Basket); ok {
		r0 = rf(ctx, basketID, productID)
	} else {
		r0 = ret.Get(0).(domain.Basket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, basketID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddItemFromSearch provides a mock function with given fields: ctx, basketID, productID, userID
func (_m *Basket) AddItemFromSearch(ctx context.Context, basketID string, productID string, userID string) (string, domain.Basket, error) {
	ret := _m.Called(ctx, basketID, productID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddItemFromSearch")
	}

	var r0 string
	var r1 domain.Basket
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, domain.Basket, error)); ok {
		return rf(ctx, basketID, productID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, basketID, productID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) domain.Basket); ok {
		r1 = rf(ctx, basketID, productID, userID)
	} else {
		r1 = ret.Get(1).(domain.Basket)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, basketID, productID, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ComputeFinancials provides a mock function with given fields: ctx, basketID
func (_m *Basket) ComputeFinancials(ctx context.Context, basketID string) (domain.Financials, error) {
	ret := _m.Called(ctx, basketID)

	if len(ret) == 0 {
		panic("no return value specified for ComputeFinancials")
	}

	var r0 domain.Financials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Financials, error)); ok {
		return rf(ctx, basketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Financials); ok {
		r0 = rf(ctx, basketID)
	} else {
		r0 = ret.Get(0).(domain.Financials)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, basketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, userID
func (_m *Basket) Create(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Basket) FindByID(ctx context.Context, id string) (domain.Basket, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Basket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Basket, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Basket); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Basket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *Basket) FindByUserID(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveItem provides a mock function with given fields: ctx, basketID, productID
func (_m *Basket) RemoveItem(ctx context.Context, basketID string, productID string) (domain.Basket, error) {
	ret := _m.Called(ctx, basketID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 domain.Basket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Basket, error)); ok {
		return rf(ctx, basketID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Basket); ok {
		r0 = rf(ctx, basketID, productID)
	} else {
		r0 = ret.Get(0).(domain.Basket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, basketID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBasket creates a new instance of Basket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBasket(t interface {
	mock.TestingT
	Cleanup(func())
}) *Basket {
	mock := &Basket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
