// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// Product is an autogenerated mock type for the Product type
type Product struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Product) FindByID(ctx context.Context, id string) (domain.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, searchTerm, page
func (_m *Product) Search(ctx context.Context, searchTerm string, page int64) (domain.ProductPage, error) {
	ret := _m.Called(ctx, searchTerm, page)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.ProductPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (domain.ProductPage, error)); ok {
		return rf(ctx, searchTerm, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) domain.ProductPage); ok {
		r0 = rf(ctx, searchTerm, page)
	} else {
		r0 = ret.Get(0).(domain.ProductPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, searchTerm, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProduct creates a new instance of Product. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *Product {
	mock := &Product{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
