// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// AddressRemote is an autogenerated mock type for the AddressRemote type
type AddressRemote struct {
	mock.Mock
}

// FindAddressesByUserID provides a mock function with given fields: ctx, userID, token
func (_m *AddressRemote) FindAddressesByUserID(ctx context.Context, userID string, token string) ([]domain.Address, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for FindAddressesByUserID")
	}

	var r0 []domain.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Address, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Address); ok {
		r0 = rf(ctx, userID, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasAddresses provides a mock function with given fields: ctx, userID, token
func (_m *AddressRemote) HasAddresses(ctx context.Context, userID string, token string) (bool, string, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for HasAddresses")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, string, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, userID, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertAddress provides a mock function with given fields: ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token
func (_m *AddressRemote) InsertAddress(ctx context.Context, userID string, addressType domain.AddressType, country string, city string, state string, zip string, mainStreet string, secondaryStreet string, numeration string, phone string, token string) (string, error) {
	ret := _m.Called(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token)

	if len(ret) == 0 {
		panic("no return value specified for InsertAddress")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AddressType, string, string, string, string, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AddressType, string, string, string, string, string, string, string, string, string) string); ok {
		r0 = rf(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AddressType, string, string, string, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAddress provides a mock function with given fields: ctx, id, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token
func (_m *AddressRemote) UpdateAddress(ctx context.Context, id string, userID string, addressType domain.AddressType, country string, city string, state string, zip string, mainStreet string, secondaryStreet string, numeration string, phone string, token string) error {
	ret := _m.Called(ctx, id, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.AddressType, string, string, string, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, userID, addressType, country, city, state, zip, mainStreet, secondaryStreet, numeration, phone, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressRemote creates a new instance of AddressRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressRemote {
	mock := &AddressRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
