// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// AuthRemote is an autogenerated mock type for the AuthRemote type
type AuthRemote struct {
	mock.Mock
}

// ActivateUser provides a mock function with given fields: ctx, token, userID, activationToken
func (_m *AuthRemote) ActivateUser(ctx context.Context, token string, userID string, activationToken string) error {
	ret := _m.Called(ctx, token, userID, activationToken)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, userID, activationToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindTokenByEmailAndPassword provides a mock function with given fields: ctx, email, password, token
func (_m *AuthRemote) FindTokenByEmailAndPassword(ctx context.Context, email string, password string, token string) (string, error) {
	ret := _m.Called(ctx, email, password, token)

	if len(ret) == 0 {
		panic("no return value specified for FindTokenByEmailAndPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, email, password, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, email, password, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, email, token
func (_m *AuthRemote) FindUserByEmail(ctx context.Context, email string, token string) (domain.User, error) {
	ret := _m.Called(ctx, email, token)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.User, error)); ok {
		return rf(ctx, email, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.User); ok {
		r0 = rf(ctx, email, token)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmailAndPassword provides a mock function with given fields: ctx, email, password, token
func (_m *AuthRemote) FindUserByEmailAndPassword(ctx context.Context, email string, password string, token string) (domain.User, error) {
	ret := _m.Called(ctx, email, password, token)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmailAndPassword")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.User, error)); ok {
		return rf(ctx, email, password, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) domain.User); ok {
		r0 = rf(ctx, email, password, token)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id, token
func (_m *AuthRemote) FindUserByID(ctx context.Context, id string, token string) (domain.User, error) {
	ret := _m.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.User, error)); ok {
		return rf(ctx, id, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.User); ok {
		r0 = rf(ctx, id, token)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserTokenByEmailAndPassword provides a mock function with given fields: ctx, email, password, token
func (_m *AuthRemote) FindUserTokenByEmailAndPassword(ctx context.Context, email string, password string, token string) (string, string, error) {
	ret := _m.Called(ctx, email, password, token)

	if len(ret) == 0 {
		panic("no return value specified for FindUserTokenByEmailAndPassword")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, string, error)); ok {
		return rf(ctx, email, password, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, email, password, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, email, password, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, email, password, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAdminToken provides a mock function with given fields: ctx
func (_m *AuthRemote) GetAdminToken(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshUserToken provides a mock function with given fields: ctx, userID, refreshToken, token
func (_m *AuthRemote) RefreshUserToken(ctx context.Context, userID string, refreshToken string, token string) (string, error) {
	ret := _m.Called(ctx, userID, refreshToken, token)

	if len(ret) == 0 {
		panic("no return value specified for RefreshUserToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, userID, refreshToken, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userID, refreshToken, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, refreshToken, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: ctx, firstName, lastName, email, password, confirmPassword, token, roleID
func (_m *AuthRemote) RegisterUser(ctx context.Context, firstName string, lastName string, email string, password string, confirmPassword string, token string, roleID string) (string, error) {
	ret := _m.Called(ctx, firstName, lastName, email, password, confirmPassword, token, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, firstName, lastName, email, password, confirmPassword, token, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) string); ok {
		r0 = rf(ctx, firstName, lastName, email, password, confirmPassword, token, roleID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, firstName, lastName, email, password, confirmPassword, token, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendResetPasswdEmail provides a mock function with given fields: ctx, email, token
func (_m *AuthRemote) SendResetPasswdEmail(ctx context.Context, email string, token string) error {
	ret := _m.Called(ctx, email, token)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswdEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserPassword provides a mock function with given fields: ctx, userID, password, confirmPassword, token
func (_m *AuthRemote) UpdateUserPassword(ctx context.Context, userID string, password string, confirmPassword string, token string) error {
	ret := _m.Called(ctx, userID, password, confirmPassword, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, password, confirmPassword, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthRemote creates a new instance of AuthRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRemote {
	mock := &AuthRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
