// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// BasketRemote is an autogenerated mock type for the BasketRemote type
type BasketRemote struct {
	mock.Mock
}

// BasketAddItem provides a mock function with given fields: ctx, id, productID, quantity, token
func (_m *BasketRemote) BasketAddItem(ctx context.Context, id string, productID string, quantity int, token string) error {
	ret := _m.Called(ctx, id, productID, quantity, token)

	if len(ret) == 0 {
		panic("no return value specified for BasketAddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string) error); ok {
		r0 = rf(ctx, id, productID, quantity, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BasketRemoveItem provides a mock function with given fields: ctx, id, productID, quantity, token
func (_m *BasketRemote) BasketRemoveItem(ctx context.Context, id string, productID string, quantity int, token string) error {
	ret := _m.Called(ctx, id, productID, quantity, token)

	if len(ret) == 0 {
		panic("no return value specified for BasketRemoveItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string) error); ok {
		r0 = rf(ctx, id, productID, quantity, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelBasket provides a mock function with given fields: ctx, id, token
func (_m *BasketRemote) CancelBasket(ctx context.Context, id string, token string) error {
	ret := _m.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for CancelBasket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckoutBasket provides a mock function with given fields: ctx, id, paymentID, shippingAddressID, token
func (_m *BasketRemote) CheckoutBasket(ctx context.Context, id string, paymentID string, shippingAddressID string, token string) error {
	ret := _m.Called(ctx, id, paymentID, shippingAddressID, token)

	if len(ret) == 0 {
		panic("no return value specified for CheckoutBasket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, id, paymentID, shippingAddressID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ComputeFinancials provides a mock function with given fields: ctx, id, token
func (_m *BasketRemote) ComputeFinancials(ctx context.Context, id string, token string) (domain.Financials, error) {
	ret := _m.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for ComputeFinancials")
	}

	var r0 domain.Financials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Financials, error)); ok {
		return rf(ctx, id, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Financials); ok {
		r0 = rf(ctx, id, token)
	} else {
		r0 = ret.Get(0).(domain.Financials)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBasket provides a mock function with given fields: ctx, userID, token
func (_m *BasketRemote) CreateBasket(ctx context.Context, userID string, token string) (string, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateBasket")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBasket provides a mock function with given fields: ctx, id, token
func (_m *BasketRemote) FindBasket(ctx context.Context, id string, token string) (domain.Basket, error) {
	ret := _m.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for FindBasket")
	}

	var r0 domain.Basket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Basket, error)); ok {
		return rf(ctx, id, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Basket); ok {
		r0 = rf(ctx, id, token)
	} else {
		r0 = ret.Get(0).(domain.Basket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBasketByUserID provides a mock function with given fields: ctx, userID, token
func (_m *BasketRemote) FindBasketByUserID(ctx context.Context, userID string, token string) (string, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for FindBasketByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBasketRemote creates a new instance of BasketRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBasketRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *BasketRemote {
	mock := &BasketRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
