// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// OrderRemote is an autogenerated mock type for the OrderRemote type
type OrderRemote struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: ctx, orderID, token
func (_m *OrderRemote) CancelOrder(ctx context.Context, orderID string, token string) error {
	ret := _m.Called(ctx, orderID, token)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteOrder provides a mock function with given fields: ctx, orderID, invoiceID, token
func (_m *OrderRemote) CompleteOrder(ctx context.Context, orderID string, invoiceID string, token string) error {
	ret := _m.Called(ctx, orderID, invoiceID, token)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orderID, invoiceID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: ctx, req, token
func (_m *OrderRemote) CreateOrder(ctx context.Context, req domain.CreateOrderRequest, token string) (string, error) {
	ret := _m.Called(ctx, req, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateOrderRequest, string) (string, error)); ok {
		return rf(ctx, req, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateOrderRequest, string) string); ok {
		r0 = rf(ctx, req, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateOrderRequest, string) error); ok {
		r1 = rf(ctx, req, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, orderID, token
func (_m *OrderRemote) GetOrder(ctx context.Context, orderID string, token string) (domain.Order, error) {
	ret := _m.Called(ctx, orderID, token)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Order, error)); ok {
		return rf(ctx, orderID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Order); ok {
		r0 = rf(ctx, orderID, token)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orderID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID, token
func (_m *OrderRemote) GetOrdersByUserID(ctx context.Context, userID string, token string) ([]domain.Order, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Order, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Order); ok {
		r0 = rf(ctx, userID, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadyOrder provides a mock function with given fields: ctx, orderID, token
func (_m *OrderRemote) ReadyOrder(ctx context.Context, orderID string, token string) error {
	ret := _m.Called(ctx, orderID, token)

	if len(ret) == 0 {
		panic("no return value specified for ReadyOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRemote creates a new instance of OrderRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRemote {
	mock := &OrderRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
