// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// PayPhoneRemote is an autogenerated mock type for the PayPhoneRemote type
type PayPhoneRemote struct {
	mock.Mock
}

// CancelPayment provides a mock function with given fields: ctx, payphoneID, clientTransactionID
func (_m *PayPhoneRemote) CancelPayment(ctx context.Context, payphoneID string, clientTransactionID string) error {
	ret := _m.Called(ctx, payphoneID, clientTransactionID)

	if len(ret) == 0 {
		panic("no return value specified for CancelPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, payphoneID, clientTransactionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmPayment provides a mock function with given fields: ctx, payphoneID, clientTransactionID
func (_m *PayPhoneRemote) ConfirmPayment(ctx context.Context, payphoneID string, clientTransactionID string) (domain.PaymentConfirmation, error) {
	ret := _m.Called(ctx, payphoneID, clientTransactionID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPayment")
	}

	var r0 domain.PaymentConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.PaymentConfirmation, error)); ok {
		return rf(ctx, payphoneID, clientTransactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.PaymentConfirmation); ok {
		r0 = rf(ctx, payphoneID, clientTransactionID)
	} else {
		r0 = ret.Get(0).(domain.PaymentConfirmation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, payphoneID, clientTransactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessPayment provides a mock function with given fields: ctx, req
func (_m *PayPhoneRemote) ProcessPayment(ctx context.Context, req domain.PaymentRequest) (domain.PaymentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 domain.PaymentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentRequest) (domain.PaymentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentRequest) domain.PaymentResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.PaymentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayPhoneRemote creates a new instance of PayPhoneRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayPhoneRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayPhoneRemote {
	mock := &PayPhoneRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
