// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/v8tix/beecore-store-v2/internal/core/domain"
)

// ProductRemote is an autogenerated mock type for the ProductRemote type
type ProductRemote struct {
	mock.Mock
}

// FindPaginatedProducts provides a mock function with given fields: ctx, searchTerm, page, token
func (_m *ProductRemote) FindPaginatedProducts(ctx context.Context, searchTerm string, page int64, token string) (domain.ProductPage, error) {
	ret := _m.Called(ctx, searchTerm, page, token)

	if len(ret) == 0 {
		panic("no return value specified for FindPaginatedProducts")
	}

	var r0 domain.ProductPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) (domain.ProductPage, error)); ok {
		return rf(ctx, searchTerm, page, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) domain.ProductPage); ok {
		r0 = rf(ctx, searchTerm, page, token)
	} else {
		r0 = ret.Get(0).(domain.ProductPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, string) error); ok {
		r1 = rf(ctx, searchTerm, page, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProduct provides a mock function with given fields: ctx, id, token
func (_m *ProductRemote) FindProduct(ctx context.Context, id string, token string) (domain.Product, error) {
	ret := _m.Called(ctx, id, token)

	if len(ret) == 0 {
		panic("no return value specified for FindProduct")
	}

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Product, error)); ok {
		return rf(ctx, id, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Product); ok {
		r0 = rf(ctx, id, token)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductRemote creates a new instance of ProductRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRemote {
	mock := &ProductRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
