// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRemote is an autogenerated mock type for the UserRemote type
type UserRemote struct {
	mock.Mock
}

// UpdateUser provides a mock function with given fields: ctx, id, dni, firstName, lastName, birthday, phone, imageURL, website, token
func (_m *UserRemote) UpdateUser(ctx context.Context, id string, dni string, firstName string, lastName string, birthday string, phone string, imageURL string, website string, token string) error {
	ret := _m.Called(ctx, id, dni, firstName, lastName, birthday, phone, imageURL, website, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, dni, firstName, lastName, birthday, phone, imageURL, website, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRemote creates a new instance of UserRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRemote {
	mock := &UserRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
